### ISSUE TITLE
Creative mode removes natural spawned blocks in epic worldgenerator

### ISSUE THREAD

**Issue by Rikk010** [GriefPrevention/GriefPrevention#841]
### What happened:
When doing /abandonallclaims in creativemode(not /abandonclaims) while in a epic worldgenerator is removes random blocks. 
Since this is probably Epic-worldgeneration's issue, maybe add an option in creativemode to not restore to nature?

### What was expected:
No blocks changing since its natural spawned

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. be in epic worldgenerated world
2. /claim
3. /abandonallclaims
4. random blocks are removed

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: `07.06 14:32:55 [Server] INFO This server is running Paper version git-Paper-322 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
07.06 14:32:55 [Server] INFO You are 13 version(s) behind`
Paste of `/version GriefPrevention`: `griefprevention version 16.13.0

### Stack trace/error or server log

```
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

```

### Plugin list (if applicable):
- epic worldgen
- griefprevention

### Debugging steps attempted

- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server

**Comment by Jikoo** [comment]
This is because when GP cleans up creative claims it doesn't regenerate chunks (which is no longer possible with the Bukkit API anyway IIRC), it tries to remove unnatural blocks. If your world gen is adding non-standard blocks, restorenature won't play well with it.

**Comment by RoboMWM** [comment]
Uhm, didn't I respond to an issue that was exactly like this?

**Comment by RoboMWM** [comment]
Duplicate of #838 

I told you how to resolve, change the claim mode in the config to something like SurvivalRequiringClaims. https://github.com/TechFortress/GriefPrevention/wiki/Setup-and-Configuration#limiting-which-worlds-griefprevention-runs-on
